### ISSUE TITLE
Portuguese - Original + Duplicado vs Single Original

### ISSUE THREAD

**Issue by eduo** [premium-minds/billy#28]
Hello, All, 

I need some help figuring out a discrepancy because I have seriously conflicting messages from different "experts".

1.According to one team of consultants, to be able to invoice in Portugal we're required always to generate an "original" and a "duplicado" (duplicate) of each and every invoice. We print/send the "original" and store the "duplicado", which is used for archival purposes. Also that the "original" invoice needs to have the word "original" in it and the "duplicado" needs to have the text instead.

Part of this team insists adding "Original" is not mandatory to the originals, but adding "Duplicado" is for the duplicates.

In this scenario the only difference between the "original" and "duplicado" is the text in the invoice.

2.According to another team of consultants if we're generating PDF Invoices then it's not necessary to store "duplicados", nor does the original need to be labeled "original" in the PDF. This is how it works for most countries normally, so I'd wish this to be the right answer.

3.According to yet another "expert" we need to print a PDF labeled "original", store a printed PDF labeled "duplicado" and then for each consecutive copy of the original (if needed) we need to add if it's the first reprint ("1ª via"), the second reprint ("2ª via") or more ("reimpressão"). I have so far figured out this is really for invoices primarily printed rather than in PDF form.

Nonetheless, I've decided all these experts are useless and I'm asking real-experience developers what's in reality required in your implementations or by Portuguese law (if possible with explanation of why this is). This is doubly important because it's a key point in being certified as an invoicing system in Portugal.

I appreciate clear pointers. I'm surprised when searching around that if option 1 is the real requirement, that people are not complaining all over the place for such a ridiculous rule.

**Comment by froque** [comment]
I am not a lawyer. 

In my application I don't store any PDF's, and I don't think you need to. The application stores all invoice documents in a relational database. When required, I just print one copy. 

I think confusion comes from [Código do Imposto sobre o Valor Acrescentado (CIVA), Artigo 36.º  Prazo de emissão e formalidades das facturas](http://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa_rep/iva36.htm)

> 4 - Os documentos referidos nos números anteriores devem ser processados em duplicado, destinando-se o original ao cliente e a cópia ao arquivo do fornecedor.

But for me, that is legacy for paper based invoices. 

The requirements for an electronic based invoice system is to encrypt some of the invoice details using a assymetric cipher, and to export a SAFT file for the portuguese authorities. 

There is some english documentation here:

- [Tax System in Portugal](http://info.portaldasfinancas.gov.pt/pt/docs/Conteudos_1pagina/NEWS_Portuguese_Tax_System.htm)
    - [Certification of computer invoicing programmes relating to the Corporate Income Tax Code](http://info.portaldasfinancas.gov.pt/NR/rdonlyres/3BE548A5-10F5-4C5F-ADE5-6625B23D7DCE/0/Ordinance_363_2010_Certification_of_computer_invoicing_programs.pdf) 
    - [SAF-T PT (Standard Audit File for Tax purposes) ](http://info.portaldasfinancas.gov.pt/NR/rdonlyres/9DD0F5D3-B2E2-43C1-9AD4-6E39A9BF23EC/0/Ordinance_274_2013_SAF_T_PT.pdf)

Perhaps you should contact oficial authorities (sdg-it@at.gov.pt). You can also check with [this portuguese programmers community](https://www.portugal-a-programar.pt/forums/)

**Comment by eduo** [comment]
Thanks for the response.

I agree with all you're saying. The requirement doesn't specify that duplicates should be labeled as such and the requirement is absurd for PDFs.

The problem is that it seems almost every system out there does the "Original"/"Duplicado" thing so it's very hard to go against this current.

Have you been able to get certification for a system that doesn't produce "duplicado" versions of PDFs?

As per the portuguese programmers forum, my portuguese is OK for reading but crap for writing, so while I can read the (lengthy) discussions on this, there doesn't seem to be any clear indication and I don't feel I'm good enough to try and write a question myself.

Aside: I should clarify this is part of updating a legacy billing system for the purpose of SAFT, which implies certifying our billing system. In 2015 I certified a different system and also completed the SAFT changes but the local business didn't bring this up and it was never considered an issue. 

In this new case the business is unsure about legislation and the consultants are being unclear on which direction to go. My experience is taken as an expert's opinion but have less weight than the consultants.

If I could have confirmation of a certified, SAFT-compliant, system that produces PDFs and doesn't generate or archive "Duplicado" versions of those files or a clear response from a legal authority or consulting firm, I could use that to defend the position.

**Comment by ajcamilo** [comment]
You do not need to store the PDF version of the "Original", neither the "Duplicado".

Your system only needs to store the invoice "data". And this data needs to be immutable! Meaning it is possible to always generate the same PDF without changes in the invoice information (the layout may change).

Some systems when are generating the PDF of the invoice, they output two documents, the "Original" and the "Duplicado", others just output one document. All are certified.

The certification focus is in the system ensure that the invoices can't be changed after emitted, that the invoices are sequencial and that no invoices are deleted.

**Comment by eduo** [comment]
hi, Ajcamilo

I appreciate what you say and I agree with you, which is why I'm looking for something I can quote from certified systems or legislation or AT decisions. 

What I keep being told by consultants and experts is that even for PDFs a "duplicado" PDF needs to be stored. And if we ever print for our customers and send the printed invoice (as a courtesy) we'd need to track not only those duplicados but also "2ª Via".

It's very frustrating knowing something makes no sense, poses an absurd amount of time challenge to develop and would result in a ridiculous "solution" but not having a way of proving it. I half-expected this to have been a discussion someone already had.

I appreciate the responses.

**Comment by ajcamilo** [comment]
Like @froque said, maybe try to contact the oficial authorities.

**Comment by eduo** [comment]
Sorry, I wasn't clear. I had already asked the AT and the programmer's forum. I just hadn't got an answer there.
