### ISSUE TITLE
HHH000183: no persistent classes found 

### ISSUE THREAD

**Issue by rojdes** [premium-minds/billy#29]
I created example according to manual from http://premium-minds.github.io/billy/
As result I received every time issue:

`WARNING: Method [public com.premiumminds.billy.portugal.services.builders.PTBusinessBuilder com.premiumminds.billy.portugal.services.builders.impl.PTBusinessBuilderImpl.setFinancialID(java.lang.String,java.lang.String)] is synthetic and is being intercepted by [com.premiumminds.billy.core.util.NotOnUpdateInterceptor@19fb8826]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
WARN [QuerySplitter] - HHH000183: no persistent classes found for query class: select e from com.premiumminds.billy.portugal.persistence.entities.jpa.JPAPTBusinessEntity e where e.uid=:uid and e.active=true order by e.entityVersion desc 
SAF-T creation errorcom.premiumminds.billy.core.exceptions.BillyRuntimeException: javax.persistence.PersistenceException: javax.persistence.PersistenceException: java.lang.ArrayIndexOutOfBoundsException: 0`

My code is attached to file

**Comment by rojdes** [comment]
[code.txt](https://github.com/premium-minds/billy/files/1603154/code.txt)

**Comment by ajcamilo** [comment]
What billy version are you using? The documentation is a little outdated.

**Comment by rojdes** [comment]
Version 3.0.0
Is there newer documentation for it?

**Comment by ajcamilo** [comment]
Unfortunately no. But I will gonna update the https://github.com/premium-minds/billy-demo-app project.

Btw, in your `persistence.xml`, are you including the `orm-billy`?

If not, please include this in your `persistence-unit`:

```
<mapping-file>META-INF/orm-billy-core.xml</mapping-file>
<mapping-file>META-INF/orm-billy-portugal.xml</mapping-file>
```

**Comment by rojdes** [comment]
After adding, I receive next issue:

`WARN [SqlExceptionHelper] - SQL Error: 23505, SQLState: 23505 
ERROR [SqlExceptionHelper] - Unique index or primary key violation: "CONSTRAINT_INDEX_9 ON PUBLIC.BILLY_CORE_BUSINESS_CONTACT(ID_CONTACT) VALUES (30, 1)"; SQL statement:
insert into BILLY_CORE_BUSINESS_CONTACT (ID_BUSINESS, ID_CONTACT) values (?, ?) [23505-190] 
SAF-T creation errorcom.premiumminds.billy.core.exceptions.BillyRuntimeException: javax.persistence.PersistenceException: javax.persistence.PersistenceException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: Unique index or primary key violation: "CONSTRAINT_INDEX_9 ON PUBLIC.BILLY_CORE_BUSINESS_CONTACT(ID_CONTACT) VALUES (30, 1)"; SQL statement:
insert into BILLY_CORE_BUSINESS_CONTACT (ID_BUSINESS, ID_CONTACT) values (?, ?) [23505-190]`

If change 
PTBusiness business = billyPortugal.businesses().persistence().create(businessBuilder);
to
PTBusiness business = businessBuilder.build(); 
it moves to end of code, but with issue

`javax.persistence.NoResultException: No entity found for query`

**Comment by rojdes** [comment]
[persistence.txt](https://github.com/premium-minds/billy/files/1603846/persistence.txt)

[pom.txt](https://github.com/premium-minds/billy/files/1603857/pom.txt)

**Comment by ajcamilo** [comment]
check out this demo: https://github.com/premium-minds/billy-demo-app

**Comment by rojdes** [comment]
I installed upgraded demo version:

As result from console:

`Business Name:
Business2
Business not found, create new? (y/n)
y
Name:
Bn
Tax Registration Number:
123456789
Street name:
Straeet
Door number:
23
Postal Code:
43026
City:
Lviv
Telephone:
+3809999999
Create App:
APpp
Jan 10, 2018 8:21:34 PM com.google.inject.internal.ProxyFactory <init>
WARNING: Method [public com.premiumminds.billy.portugal.services.builders.PTBusinessBuilder com.premiumminds.billy.portugal.services.builders.impl.PTBusinessBuilderImpl.setFinancialID(java.lang.String,java.lang.String)] is synthetic and is being intercepted by [com.premiumminds.billy.core.util.NotOnUpdateInterceptor@7c71c889]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
Jan 10, 2018 8:21:34 PM com.google.inject.internal.ProxyFactory <init>
WARNING: Method [public com.premiumminds.billy.core.services.builders.impl.BusinessBuilderImpl com.premiumminds.billy.portugal.services.builders.impl.PTBusinessBuilderImpl.setFinancialID(java.lang.String,java.lang.String) throws com.premiumminds.billy.core.exceptions.BillyUpdateException] is synthetic and is being intercepted by [com.premiumminds.billy.core.util.NotOnUpdateInterceptor@7c71c889]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
Jan 10, 2018 8:21:34 PM com.google.inject.internal.ProxyFactory <init>
WARNING: Method [public com.premiumminds.billy.core.services.builders.BusinessBuilder com.premiumminds.billy.portugal.services.builders.impl.PTBusinessBuilderImpl.setFinancialID(java.lang.String,java.lang.String)] is synthetic and is being intercepted by [com.premiumminds.billy.core.util.NotOnUpdateInterceptor@7c71c889]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
[ERROR] An error ocurred: com.premiumminds.billy.core.exceptions.BillyRuntimeException: com.premiumminds.billy.core.exceptions.BillyValidationException
From date: (dd/mm/yyyy)`

Also I tried implement code from example 1.0.0:

`Exception in thread "main" javax.validation.ValidationException: !exception.invalid_taxes!
	at com.premiumminds.billy.core.services.builders.impl.GenericInvoiceEntryBuilderImpl.validateValues(GenericInvoiceEntryBuilderImpl.java:261)
	at com.premiumminds.billy.core.services.builders.impl.GenericInvoiceEntryBuilderImpl.validateInstance(GenericInvoiceEntryBuilderImpl.java:228)
	at com.premiumminds.billy.portugal.services.builders.impl.PTGenericInvoiceEntryBuilderImpl.validateInstance(PTGenericInvoiceEntryBuilderImpl.java:64)
	at com.premiumminds.billy.portugal.services.builders.impl.PTInvoiceEntryBuilderImpl.validateInstance(PTInvoiceEntryBuilderImpl.java:55)
	at com.premiumminds.billy.core.services.builders.impl.AbstractBuilder.build(AbstractBuilder.java:64)
	at com.premiumminds.billy.core.services.builders.impl.GenericInvoiceBuilderImpl.addEntry(GenericInvoiceBuilderImpl.java:203)
	at com.premiumminds.billy.core.util.NotOnUpdateInterceptor.invoke(NotOnUpdateInterceptor.java:52)`
exception in invoiceBuilder.addEntry(entryBuilder); raw (code the same as above)

**Comment by rojdes** [comment]
For starting demo, I installed PostgreSQL.
Is any possibility to make Billy portable, without any additional installation (for ex. use Sqlite db file)?

**Comment by ajcamilo** [comment]
@rojdes, Billy uses Hibernate (or Ebean, but this is still in heavy development).

This means Billy supports all databases that hibernate supports.

**Comment by rojdes** [comment]
@ajcamilo, thank you. 
What do you think about exceptions?

**Comment by rojdes** [comment]
@ajcamilo 
I could create xsl file, according next data
_Business Name:
Bus5
Business not found, create new? (y/n)
y
Name:
Bus5
Tax Registration Number:
500303568
Street name:
Street
Door number:
21
Postal Code:
1000-100
City:
Lviv
Telephone:
+380993103101
Create App:
app
Jan 11, 2018 7:56:54 PM com.google.inject.internal.ProxyFactory <init>
WARNING: Method [public com.premiumminds.billy.portugal.services.builders.PTBusinessBuilder com.premiumminds.billy.portugal.services.builders.impl.PTBusinessBuilderImpl.setFinancialID(java.lang.String,java.lang.String)] is synthetic and is being intercepted by [com.premiumminds.billy.core.util.NotOnUpdateInterceptor@7c71c889]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
Jan 11, 2018 7:56:54 PM com.google.inject.internal.ProxyFactory <init>
WARNING: Method [public com.premiumminds.billy.core.services.builders.impl.BusinessBuilderImpl com.premiumminds.billy.portugal.services.builders.impl.PTBusinessBuilderImpl.setFinancialID(java.lang.String,java.lang.String) throws com.premiumminds.billy.core.exceptions.BillyUpdateException] is synthetic and is being intercepted by [com.premiumminds.billy.core.util.NotOnUpdateInterceptor@7c71c889]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
Jan 11, 2018 7:56:54 PM com.google.inject.internal.ProxyFactory <init>
WARNING: Method [public com.premiumminds.billy.core.services.builders.BusinessBuilder com.premiumminds.billy.portugal.services.builders.impl.PTBusinessBuilderImpl.setFinancialID(java.lang.String,java.lang.String)] is synthetic and is being intercepted by [com.premiumminds.billy.core.util.NotOnUpdateInterceptor@7c71c889]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.
Business: Bus5 created.
From date: (dd/mm/yyyy)
11/12/2016_

But i couldn't create it using code from example 

`WARN [SqlExceptionHelper] - SQL Error: 0, SQLState: 23505 ERROR [SqlExceptionHelper] - ERROR: duplicate key value violates unique constraint "uk_kxud4abkdtm5b34i5nkwghv7l" Detail: Key (id_contact)=(3) already exists. Exception in thread "main" `
