### ISSUE TITLE
impossibilty of configuring the default persist unit

### ISSUE THREAD

**Issue by madskaddie** [premium-minds/billy#9]
The default constructor of BillyPortugal mandates that the persistence unit be named as "BillyPortugalPersistenceUnit". This should be a parameter

**Comment by miroxo** [comment]
The persistence-unit is meant to be provided by the client application, though it isn't clear

**Comment by froque** [comment]
This can be a parameter since commit https://github.com/premium-minds/billy/commit/ca47c42103ecc7db7936c19f889fbfd2577025f7
